<a href="https://colab.research.google.com/github/sasi-nk/BSC_DPDM2025/blob/main/Midterm_663020297_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ข้อ 1 อ่านไฟล์ทั้งหมด

In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [3]:
his_daily_rainfall = pd.read_csv('/content/drive/MyDrive/BSC DPDM midterm 2025/Daily rain - (Statistics 2012-2024)/hii_daily_rain.csv')
his_daily_rainfall.head()

,station_code,measure_datetime,data,station_name,latitude,longitude,quality_flag,basin,sub_basin,tambon,amphoe,province,data_type
0,ABRT,2012-01-01 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
1,ABRT,2012-01-03 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
2,ABRT,2012-01-06 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
3,ABRT,2012-01-07 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily
4,ABRT,2012-01-08 07:00:00+07,0.0,วัดเวฬุวัน,16.054785,103.66429,U,ชี,ลำน้ำชีส่วนที่ 4/2,เหนือเมือง,เมืองร้อยเอ็ด,ร้อยเอ็ด,rainfall_daily

In [14]:
#กำหนดพาธไปยังโฟลเดอร์ที่ต้องการอ่าน
path_07 = '/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-07'
path_08 = '/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-08'
path_09 = '/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-09'
path_10 = '/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-10'
path_11 = '/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-11'
path_12 = '/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-12'

#### Input 2025-07

In [15]:
# ระบุพาธแบบสมบูรณ์ของโฟลเดอร์ที่มีไฟล์ CSV ทั้งหมดที่ต้องการรวมเข้าด้วยกัน
print(f"Path for 2025-07: {path_07}")

# วนลูปผ่านไฟล์ทั้งหมดในโฟลเดอร์ที่ระบุ ค้นหาเฉพาะไฟล์ CSV อ่านแต่ละไฟล์เข้าสู่ pandas DataFrame และเก็บ DataFrame เหล่านี้ไว้ในลิสต์
# Create an empty list to store the DataFrames
dfs_to_concat = []

# List all files and directories in the specified path
for filename in os.listdir(path_07):
    # Check if the file is a CSV file
    if filename.endswith('.csv'):
        # Construct the full file path
        file_path = os.path.join(path_07, filename)
        # Read the CSV file into a pandas DataFrame
        df = pd.read_csv(file_path)
        # Append the DataFrame to the list
        dfs_to_concat.append(df)

print(f"Found {len(dfs_to_concat)} CSV files and loaded them into a list of DataFrames.")

Path for 2025-07: /content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-07
Found 31 CSV files and loaded them into a list of DataFrames.

In [16]:
# รวมให้อยู่ในตารางเดียวกัน
combined_df_07 = pd.concat(dfs_to_concat, ignore_index=True)
combined_df_07.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139,BLKO,2025-07-09
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277,BNAK,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156,BPK004,2025-07-09

In [18]:
combined_df_07.shape

(27875, 6)

#### Input 2025-08

In [21]:
# ระบุพาธแบบสมบูรณ์ของโฟลเดอร์ที่มีไฟล์ CSV ทั้งหมดที่ต้องการรวมเข้าด้วยกัน
print(f"Path for 2025-08: {path_08}")

# วนลูปผ่านไฟล์ทั้งหมดในโฟลเดอร์ที่ระบุ ค้นหาเฉพาะไฟล์ CSV อ่านแต่ละไฟล์เข้าสู่ pandas DataFrame และเก็บ DataFrame เหล่านี้ไว้ในลิสต์
# Create an empty list to store the DataFrames
dfs_to_concat = []

# List all files and directories in the specified path
for filename in os.listdir(path_08):
    # Check if the file is a CSV file
    if '.csv' in filename and 'daily' in filename:
        # Construct the full file path
        file_path = os.path.join(path_08, filename)
        # Read the CSV file into a pandas DataFrame
        df = pd.read_csv(file_path)
        # Append the DataFrame to the list
        dfs_to_concat.append(df)

print(f"Found {len(dfs_to_concat)} CSV files and loaded them into a list of DataFrames.")

Path for 2025-08: /content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-08
Found 31 CSV files and loaded them into a list of DataFrames.

In [22]:
# รวมให้อยู่ในตารางเดียวกัน
combined_df_08 = pd.concat(dfs_to_concat, ignore_index=True)
combined_df_08.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,575571.0,BKC007,2025-08-02
1,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,1512928.0,NaN,2025-08-02
2,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,1512927.0,NaN,2025-08-02
3,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,9.0,1395256.0,NaN,2025-08-02
4,2025-08-03 00:00:00+07:00,2025-08-03T07:00:00+07:00,0.0,1395255.0,NaN,2025-08-02

In [23]:
combined_df_08.shape

(27915, 6)

#### Input 2025-09

In [26]:
# ระบุพาธแบบสมบูรณ์ของโฟลเดอร์ที่มีไฟล์ CSV ทั้งหมดที่ต้องการรวมเข้าด้วยกัน
print(f"Path for 2025-09: {path_09}")

# วนลูปผ่านไฟล์ทั้งหมดในโฟลเดอร์ที่ระบุ ค้นหาเฉพาะไฟล์ CSV อ่านแต่ละไฟล์เข้าสู่ pandas DataFrame และเก็บ DataFrame เหล่านี้ไว้ในลิสต์
# Create an empty list to store the DataFrames
dfs_to_concat = []

# List all files and directories in the specified path
for filename in os.listdir(path_09):
    # Check if the file is a CSV file
    if '.csv' in filename and 'daily' in filename:
        # Construct the full file path
        file_path = os.path.join(path_09, filename)
        # Read the CSV file into a pandas DataFrame
        df = pd.read_csv(file_path)
        # Append the DataFrame to the list
        dfs_to_concat.append(df)

print(f"Found {len(dfs_to_concat)} CSV files and loaded them into a list of DataFrames.")

Path for 2025-09: /content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-09
Found 30 CSV files and loaded them into a list of DataFrames.

In [29]:
# รวมให้อยู่ในตารางเดียวกัน
combined_df_09 = pd.concat(dfs_to_concat, ignore_index=True)
combined_df_09.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,2.4,1109572.0,ONE083,2025-09-23
1,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,0.8,672.0,WTBT,2025-09-23
2,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,23.4,671.0,DIV002,2025-09-23
3,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,0.2,854.0,TSDO,2025-09-23
4,2025-09-24 00:00:00+07:00,2025-09-24T07:00:00+07:00,0.2,611.0,DIV005,2025-09-23

In [30]:
combined_df_09.shape

(27796, 6)

#### Input 2025-10

In [31]:
# ระบุพาธแบบสมบูรณ์ของโฟลเดอร์ที่มีไฟล์ CSV ทั้งหมดที่ต้องการรวมเข้าด้วยกัน
print(f"Path for 2025-10: {path_10}")

# วนลูปผ่านไฟล์ทั้งหมดในโฟลเดอร์ที่ระบุ ค้นหาเฉพาะไฟล์ CSV อ่านแต่ละไฟล์เข้าสู่ pandas DataFrame และเก็บ DataFrame เหล่านี้ไว้ในลิสต์
# Create an empty list to store the DataFrames
dfs_to_concat = []

# List all files and directories in the specified path
for filename in os.listdir(path_10):
    # Check if the file is a CSV file
    if '.csv' in filename and 'daily' in filename:
        # Construct the full file path
        file_path = os.path.join(path_10, filename)
        # Read the CSV file into a pandas DataFrame
        df = pd.read_csv(file_path)
        # Append the DataFrame to the list
        dfs_to_concat.append(df)

print(f"Found {len(dfs_to_concat)} CSV files and loaded them into a list of DataFrames.")

Path for 2025-10: /content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-10
Found 31 CSV files and loaded them into a list of DataFrames.

In [32]:
# รวมให้อยู่ในตารางเดียวกัน
combined_df_10 = pd.concat(dfs_to_concat, ignore_index=True)
combined_df_10.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,417,VLGE04,2025-10-07
1,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,464,WAN002,2025-10-07
2,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,898,VLGE42,2025-10-07
3,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.2,1198626,TRD005,2025-10-07
4,2025-10-08 00:00:00+07:00,2025-10-07T07:00:00+07:00,0.0,698,WCBR,2025-10-07

In [33]:
combined_df_10.shape

(29515, 6)

#### Input 2025-11

In [34]:
# ระบุพาธแบบสมบูรณ์ของโฟลเดอร์ที่มีไฟล์ CSV ทั้งหมดที่ต้องการรวมเข้าด้วยกัน
print(f"Path for 2025-11: {path_11}")

# วนลูปผ่านไฟล์ทั้งหมดในโฟลเดอร์ที่ระบุ ค้นหาเฉพาะไฟล์ CSV อ่านแต่ละไฟล์เข้าสู่ pandas DataFrame และเก็บ DataFrame เหล่านี้ไว้ในลิสต์
# Create an empty list to store the DataFrames
dfs_to_concat = []

# List all files and directories in the specified path
for filename in os.listdir(path_11):
    # Check if the file is a CSV file
    if '.csv' in filename and 'daily' in filename:
        # Construct the full file path
        file_path = os.path.join(path_11, filename)
        # Read the CSV file into a pandas DataFrame
        df = pd.read_csv(file_path)
        # Append the DataFrame to the list
        dfs_to_concat.append(df)

print(f"Found {len(dfs_to_concat)} CSV files and loaded them into a list of DataFrames.")

Path for 2025-11: /content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-11
Found 30 CSV files and loaded them into a list of DataFrames.

In [35]:
# รวมให้อยู่ในตารางเดียวกัน
combined_df_11 = pd.concat(dfs_to_concat, ignore_index=True)
combined_df_11.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,0.0,455701,ONWR02,2025-11-07
1,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,11.6,1109584,ONE095,2025-11-07
2,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,15.4,618,SKG005,2025-11-07
3,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,26.0,278,TKPP,2025-11-07
4,2025-11-08 00:00:00+07:00,2025-11-07T07:00:00+07:00,0.0,1109580,ONE091,2025-11-07

In [36]:
combined_df_11.shape

(31086, 6)

#### Input 2025-12

In [37]:
# ระบุพาธแบบสมบูรณ์ของโฟลเดอร์ที่มีไฟล์ CSV ทั้งหมดที่ต้องการรวมเข้าด้วยกัน
print(f"Path for 2025-12: {path_12}")

# วนลูปผ่านไฟล์ทั้งหมดในโฟลเดอร์ที่ระบุ ค้นหาเฉพาะไฟล์ CSV อ่านแต่ละไฟล์เข้าสู่ pandas DataFrame และเก็บ DataFrame เหล่านี้ไว้ในลิสต์
# Create an empty list to store the DataFrames
dfs_to_concat = []

# List all files and directories in the specified path
for filename in os.listdir(path_12):
    # Check if the file is a CSV file
    if '.csv' in filename and 'daily' in filename:
        # Construct the full file path
        file_path = os.path.join(path_12, filename)
        # Read the CSV file into a pandas DataFrame
        df = pd.read_csv(file_path)
        # Append the DataFrame to the list
        dfs_to_concat.append(df)

print(f"Found {len(dfs_to_concat)} CSV files and loaded them into a list of DataFrames.")

Path for 2025-12: /content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/2025-12
Found 31 CSV files and loaded them into a list of DataFrames.

In [38]:
# รวมให้อยู่ในตารางเดียวกัน
combined_df_12 = pd.concat(dfs_to_concat, ignore_index=True)
combined_df_12.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,1109576,ONE087,2025-12-02
1,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,135,VLGE03,2025-12-02
2,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,134,TRD004,2025-12-02
3,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,114,UTOG,2025-12-02
4,2025-12-03 00:00:00+07:00,2025-12-02T07:00:00+07:00,0.0,103,TB0004,2025-12-02

In [39]:
combined_df_12.shape

(32699, 6)



---

In [40]:
station_info = pd.read_csv('/content/drive/MyDrive/BSC DPDM midterm 2025/Input - (Operation Daily rain from API_ 2025)/Stations in the model_HII.csv')
station_info.head()

   Node        Lat        Long
0  ACRU  15.788054  104.642235
1  BBHN   9.536913   98.579490
2  BBUA  17.372976  103.984436
3  BCNG  17.386840  103.290870
4  BDAR  14.587073  102.495190

In [41]:
output_df = pd.read_csv('/content/drive/MyDrive/BSC DPDM midterm 2025/Output - (Clean monthly rain - 2025)/Y_monthly_rain_HII_operation.csv')
output_df.head()

   Node   rain  month  year
0  ACRU   83.0      7  2025
1  ACRU  164.8      8  2025
2  ACRU  248.6      9  2025
3  ACRU   48.4     10  2025
4  ACRU   52.2     11  2025

# ข้อ 2 กรองข้อมูล

In [87]:
# รวมตารางทุกเดียวมาไว้ด้วยกัน
combined_df = pd.concat([combined_df_07, combined_df_08, combined_df_09, combined_df_10, combined_df_11, combined_df_12], ignore_index=True)
combined_df

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09
3,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,277.0,BNAK,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
...,...,...,...,...,...,...
176881,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,254.0,BJAN,2025-12-13
176882,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,308.0,WEI012,2025-12-13
176883,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,770.0,GLF003,2025-12-13
176884,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,1109588.0,ONE099,2025-12-13
176885,2025-12-14 00:00:00+07:00,2025-12-13T07:00:00+07:00,0.0,286.0,TSUD,2025-12-13

นับสถานีทั้งหมดก่อนกรอง

In [46]:
unique_station_count = combined_df['tele_station_oldcode'].nunique()
print(f"จำนวนสถานีที่ไม่ซ้ำกันทั้งหมด: {unique_station_count}")

จำนวนสถานีที่ไม่ซ้ำกันทั้งหมด: 1514

กรองให้เหลือแค่สถานีที่มีในไฟล์ Station_info

#### ดึงค่าที่ไม่ซ้ำกันจากทั้งสองคอลัมน์


ดึงรายการค่าที่ไม่ซ้ำกันจากคอลัมน์ `tele_station_oldcode` ใน `combined_df` และจากคอลัมน์ `Node` ใน `station_info`

In [50]:
unique_tele_station_oldcode = combined_df['tele_station_oldcode'].dropna().unique()
unique_node_station = station_info['Node'].dropna().unique()

In [52]:
common_station_codes = np.intersect1d(unique_tele_station_oldcode, unique_node_station)
print(f"Common station codes found: {len(common_station_codes)}")
print("Common station codes (first 10):", common_station_codes[:10])

Common station codes found: 384
Common station codes (first 10): ['ACRU' 'BBHN' 'BBUA' 'BCNG' 'BDAR' 'BDCP' 'BDGN' 'BDLH' 'BDMG' 'BGRT']

In [88]:
filtered_combined_df = combined_df[combined_df['tele_station_oldcode'].isin(common_station_codes)]
print(f"Original combined_df shape: {combined_df.shape}")
print(f"Filtered combined_df shape: {filtered_combined_df.shape}")
filtered_combined_df.head()

Original combined_df shape: (176886, 6)
Filtered combined_df shape: (66275, 6)

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09

# ข้อ 3 ระบุข้อมูลสูญหาย

In [60]:
filtered_combined_df.isnull().sum()

rainfall_datetime            0
rainfall_datetime_calc       0
rainfall_value               1
tele_station_id           1023
tele_station_oldcode         0
measure_datetime             0
dtype: int64

In [63]:
# Group by 'tele_station_oldcode' and sum nulls in 'rainfall_value' and 'tele_station_id'
missing_per_station = filtered_combined_df.groupby('tele_station_oldcode')[['rainfall_value', 'tele_station_id']].apply(lambda x: x.isnull().sum())

# Filter to show only stations with missing rainfall values in either 'rainfall_value' or 'tele_station_id'
# แก้ไข: ใช้ missing_per_station แทน missingl_station และกรองสถานีที่มีค่าสูญหายมากกว่า 0 ในคอลัมน์ใดคอลัมน์หนึ่ง
missing_per_station_filtered = missing_per_station[(missing_per_station['rainfall_value'] > 0) | (missing_per_station['tele_station_id'] > 0)]

if not missing_per_station_filtered.empty:
    print("จำนวนข้อมูลที่สูญหายไปในแต่ละสถานี (ในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id'):")
    display(missing_per_station_filtered.sort_values(by=['rainfall_value', 'tele_station_id'], ascending=False))
else:
    print("ไม่พบข้อมูลที่สูญหายไปในสถานีใดๆ ในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id'")

จำนวนข้อมูลที่สูญหายไปในแต่ละสถานี (ในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id'):

                      rainfall_value  tele_station_id
tele_station_oldcode
KKTO                               1                0
ACRU                               0                3
BBHN                               0                3
BBUA                               0                3
BCNG                               0                3
...                              ...              ...
MMMO                               0                1
NBON                               0                1
NGNG                               0                1
VLGE03                             0                1
VLGE31                             0                1

[350 rows x 2 columns]

#### คำนวณสัดส่วนข้อมูลที่สูญหายไปของแต่ละสถานี

In [64]:
# 1. คำนวณจำนวนข้อมูลทั้งหมดของแต่ละสถานี
total_records_per_station = filtered_combined_df.groupby('tele_station_oldcode').size().rename('total_records')

# 2. รวมข้อมูลที่หายไปกับจำนวนข้อมูลทั้งหมด
# ใช้ .reset_index() เพื่อให้ 'tele_station_oldcode' เป็นคอลัมน์ปกติสำหรับการ merge
missing_data_merged = missing_per_station_filtered.reset_index().merge(
    total_records_per_station.reset_index(),
    on='tele_station_oldcode',
    how='left'
)

# 3. คำนวณสัดส่วนข้อมูลที่หายไป
missing_data_merged['proportion_rainfall_missing'] = missing_data_merged['rainfall_value'] / missing_data_merged['total_records']
missing_data_merged['proportion_tele_station_id_missing'] = missing_data_merged['tele_station_id'] / missing_data_merged['total_records']

# จัดรูปแบบผลลัพธ์ให้เป็นสถานีและสัดส่วน
missing_proportions = missing_data_merged[['tele_station_oldcode', 'proportion_rainfall_missing', 'proportion_tele_station_id_missing']]

if not missing_proportions.empty:
    print("สัดส่วนข้อมูลที่สูญหายไปของแต่ละสถานี (แสดงเฉพาะสถานีที่มีข้อมูลหาย):")
    # จัดเรียงตามสัดส่วนที่หายไปมากที่สุด
    display(missing_proportions.sort_values(by=['proportion_rainfall_missing', 'proportion_tele_station_id_missing'], ascending=False).round(4))
else:
    print("ไม่พบข้อมูลที่สูญหายไปในสถานีใดๆ ในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id'")

สัดส่วนข้อมูลที่สูญหายไปของแต่ละสถานี (แสดงเฉพาะสถานีที่มีข้อมูลหาย):

,tele_station_oldcode,proportion_rainfall_missing,proportion_tele_station_id_missing
114,KKTO,0.0068,0.0000
146,MEWG,0.0000,0.0390
53,CEHM,0.0000,0.0357
344,YOM001,0.0000,0.0303
233,SKE001,0.0000,0.0219
...,...,...,...
317,VLGE31,0.0000,0.0067
164,NBON,0.0000,0.0059
168,NGNG,0.0000,0.0057
139,LNRG,0.0000,0.0055
313,VLGE03,0.0000,0.0055

# ข้อ 4 คัดสถานีที่มีข้อมูลหาย >= 20%

In [78]:
# กรองสถานีที่มีสัดส่วนข้อมูล 'rainfall_value' หรือ 'tele_station_id' สูญหาย >= 20% (0.20)
stations_with_high_missing_data = missing_proportions[
    (missing_proportions['proportion_rainfall_missing'] >= 0.20) |
    (missing_proportions['proportion_tele_station_id_missing'] >= 0.20)
]

if not stations_with_high_missing_data.empty:
    print("สถานีที่มีข้อมูลสูญหาย >= 20% ในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id':")
    display(stations_with_high_missing_data.sort_values(by=['proportion_rainfall_missing', 'proportion_tele_station_id_missing'], ascending=False).round(4))
    # สามารถเก็บรายชื่อสถานีเหล่านี้ไว้ในตัวแปรเพื่อใช้ในการกรอง DataFrame หลักในขั้นตอนต่อไปได้
    stations_to_exclude = stations_with_high_missing_data['tele_station_oldcode'].tolist()
    print("\nรายชื่อสถานีที่ควรถูกคัดออก:", stations_to_exclude)
else:
    print("ไม่พบสถานีใดๆ ที่มีข้อมูลสูญหายตั้งแต่ 20% ขึ้นไปในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id'")

ไม่พบสถานีใดๆ ที่มีข้อมูลสูญหายตั้งแต่ 20% ขึ้นไปในคอลัมน์ 'rainfall_value' หรือ 'tele_station_id'

# ข้อ 5 เติมข้อมูลที่หายไป

### ขั้นตอนที่ 1: เตรียมข้อมูล `his_daily_rainfall`
ขั้นตอนนี้จะแปลงคอลัมน์วันที่ใน `his_daily_rainfall` ให้เป็นรูปแบบ `datetime` สร้างคอลัมน์ `DayOfYear` และคำนวณค่ามัธยฐานของปริมาณน้ำฝน (`data`) โดยจัดกลุ่มตาม `station_code` และ `DayOfYear` เพื่อใช้เป็นตารางค้นหาสำหรับเติมข้อมูลที่หายไป

In [89]:
filtered_combined_df.head()

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,tele_station_oldcode,measure_datetime
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09

In [90]:
his_daily_rainfall['measure_datetime'] = pd.to_datetime(his_daily_rainfall['measure_datetime'])
his_daily_rainfall['Day_Of_Year'] = his_daily_rainfall['measure_datetime'].dt.dayofyear

median_rainfall_lookup = his_daily_rainfall.groupby(['station_code', 'Day_Of_Year'])['data'].median().reset_index()
median_rainfall_lookup.rename(columns={'data': 'median_daily_rainfall'}, inplace=True)

print("แปลง 'measure_datetime' เป็นรูปแบบ datetime, สร้าง 'Day_Of_Year' และคำนวณตารางค้นหาค่ามัธยฐานปริมาณน้ำฝน")
display(median_rainfall_lookup.head())

แปลง 'measure_datetime' เป็นรูปแบบ datetime, สร้าง 'Day_Of_Year' และคำนวณตารางค้นหาค่ามัธยฐานปริมาณน้ำฝน

  station_code  Day_Of_Year  median_daily_rainfall
0         ABRT            1                    0.0
1         ABRT            2                    0.0
2         ABRT            3                    0.0
3         ABRT            4                    0.0
4         ABRT            5                    0.0

In [91]:
filtered_combined_df['measure_datetime'] = pd.to_datetime(filtered_combined_df['measure_datetime'])
filtered_combined_df['Day_Of_Year'] = filtered_combined_df['measure_datetime'].dt.dayofyear
filtered_combined_df.rename(columns={'tele_station_oldcode': 'station_code'}, inplace=True)

print("แปลง 'measure_datetime' เป็นรูปแบบ datetime, สร้าง 'Day_Of_Year' และเปลี่ยนชื่อคอลัมน์ 'tele_station_oldcode' เป็น 'station_code' ใน filtered_combined_df")
display(filtered_combined_df.head())

แปลง 'measure_datetime' เป็นรูปแบบ datetime, สร้าง 'Day_Of_Year' และเปลี่ยนชื่อคอลัมน์ 'tele_station_oldcode' เป็น 'station_code' ใน filtered_combined_df

/tmp/ipython-input-3534188117.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_combined_df['measure_datetime'] = pd.to_datetime(filtered_combined_df['measure_datetime'])
/tmp/ipython-input-3534188117.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_combined_df['Day_Of_Year'] = filtered_combined_df['measure_datetime'].dt.dayofyear
/tmp/ipython-input-3534188117.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_combined_df.rename(columns={'tele_station_oldcode': 'station_code'}, inplace=True)

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime,Day_Of_Year
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09,190
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09,190
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09,190
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09,190
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09,190

In [92]:
filtered_combined_df.isnull().sum()

rainfall_datetime            0
rainfall_datetime_calc       0
rainfall_value               1
tele_station_id           1023
station_code                 0
measure_datetime             0
Day_Of_Year                  0
dtype: int64

# ข้อ 6อธิบายว่าทำไมถึงใช้ Median แทน Mean

# ข้อ 7 คำนวณปริมาณน้ำฝนรายเดือน

# Task
คำนวณปริมาณน้ำฝนรายเดือนจาก `filtered_combined_df` โดยสร้างคอลัมน์ `month` และ `year` จาก `measure_datetime` จากนั้นจัดกลุ่มข้อมูลตาม `station_code`, `year`, และ `month` แล้วรวม `rainfall_value` เปลี่ยนชื่อคอลัมน์ `station_code` เป็น `Node` และผลรวม `rainfall_value` เป็น `rain` และแสดงผลลัพธ์ 5 แถวแรก.

## สร้างคอลัมน์เดือนและปี

### Subtask:
แปลงคอลัมน์ `measure_datetime` ใน `filtered_combined_df` ให้เป็นรูปแบบ Datetime ถ้ายังไม่ได้ทำ แล้วสร้างคอลัมน์ใหม่ `month` และ `year` โดยดึงค่ามาจาก `measure_datetime`

**Reasoning**:
The 'measure_datetime' column has already been converted to datetime type in a previous step. I will now extract the month and year from this column to create new 'month' and 'year' columns in the 'filtered_combined_df' DataFrame as requested by the subtask instructions.

In [93]:
filtered_combined_df['month'] = filtered_combined_df['measure_datetime'].dt.month
filtered_combined_df['year'] = filtered_combined_df['measure_datetime'].dt.year

print("สร้างคอลัมน์ 'month' และ 'year' จากคอลัมน์ 'measure_datetime' สำเร็จแล้ว")
display(filtered_combined_df.head())

สร้างคอลัมน์ 'month' และ 'year' จากคอลัมน์ 'measure_datetime' สำเร็จแล้ว

/tmp/ipython-input-1731424315.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_combined_df['month'] = filtered_combined_df['measure_datetime'].dt.month
/tmp/ipython-input-1731424315.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  filtered_combined_df['year'] = filtered_combined_df['measure_datetime'].dt.year

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime,Day_Of_Year,month,year
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09,190,7,2025
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09,190,7,2025
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09,190,7,2025
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09,190,7,2025
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09,190,7,2025

**Reasoning**:
The previous code produced a `SettingWithCopyWarning`. Although the columns were added, this warning indicates potential issues when modifying a DataFrame that is a slice of another DataFrame. To resolve this, I will explicitly create a copy of `filtered_combined_df` before adding new columns, ensuring that modifications are made on an independent DataFrame.

In [94]:
filtered_combined_df = filtered_combined_df.copy()
filtered_combined_df['month'] = filtered_combined_df['measure_datetime'].dt.month
filtered_combined_df['year'] = filtered_combined_df['measure_datetime'].dt.year

print("สร้างคอลัมน์ 'month' และ 'year' จากคอลัมน์ 'measure_datetime' สำเร็จแล้ว")
display(filtered_combined_df.head())

สร้างคอลัมน์ 'month' และ 'year' จากคอลัมน์ 'measure_datetime' สำเร็จแล้ว

,rainfall_datetime,rainfall_datetime_calc,rainfall_value,tele_station_id,station_code,measure_datetime,Day_Of_Year,month,year
0,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,306.0,BJIG,2025-07-09,190,7,2025
1,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,466.0,BNAN,2025-07-09,190,7,2025
2,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,27.8,139.0,BLKO,2025-07-09,190,7,2025
4,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.0,156.0,BPK004,2025-07-09,190,7,2025
5,2025-07-10 00:00:00+07:00,2025-07-10T07:00:00+07:00,0.6,294.0,BNMK,2025-07-09,190,7,2025

In [95]:
monthly_rainfall = filtered_combined_df.groupby(['station_code', 'year', 'month'])['rainfall_value'].sum().reset_index()
monthly_rainfall.rename(columns={'station_code': 'Node', 'rainfall_value': 'rain'}, inplace=True)

print("คำนวณปริมาณน้ำฝนรายเดือนเสร็จสมบูรณ์:")
display(monthly_rainfall.head())

คำนวณปริมาณน้ำฝนรายเดือนเสร็จสมบูรณ์:

   Node  year  month   rain
0  ACRU  2025      7   83.0
1  ACRU  2025      8  164.8
2  ACRU  2025      9  248.6
3  ACRU  2025     10   48.4
4  ACRU  2025     11   52.2

In [97]:
# กำหนดพาธสำหรับบันทึกไฟล์ CSV โดยเพิ่มชื่อไฟล์และนามสกุล
output_file_path = '/content/drive/MyDrive/Midterm_BSC DPDM_663020297-1/monthly_rainfall_output.csv'

# บันทึก DataFrame 'monthly_rainfall' เป็นไฟล์ CSV
monthly_rainfall.to_csv(output_file_path, index=False)

print(f"บันทึกไฟล์ monthly_rainfall_output.csv ได้ที่: {output_file_path}")

บันทึกไฟล์ monthly_rainfall_output.csv ได้ที่: /content/drive/MyDrive/Midterm_BSC DPDM_663020297-1/monthly_rainfall_output.csv

[โฟลเดอร์](https://drive.google.com/drive/folders/1WcaNCpV0_EikmbS5cerVhFZgc1kE9kxo?usp=sharing
)